---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-server
spec:
  dependsOn:
  - name: ingress-nginx
  - name: democratic-csi
  interval: 1m0s
  path: ./apps/media-server/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system