---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
spec:
  interval: 1m0s
  path: ./infrastructure/democratic-csi/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  interval: 1m0s
  path: ./infrastructure/cert-manager/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 1m0s
  path: ./infrastructure/metallb/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  dependsOn:
  - name: cert-manager
  interval: 1m0s
  path: ./infrastructure/ingress-nginx/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-capacitor
spec:
  dependsOn:
  - name: ingress-nginx
  interval: 1m0s
  path: ./infrastructure/flux-capacitor/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
spec:
  dependsOn: []
  interval: 1m0s
  path: ./infrastructure/metrics-server/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system