---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cluster-config
spec:
  interval: 1m0s
  path: ./infrastructure/cert-manager/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: cluster-config
spec:
  interval: 1m0s
  path: ./infrastructure/metallb/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  dependsOn:
  - name: cert-manager
  interval: 1m0s
  path: ./infrastructure/ingress-nginx/overlays/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: cluster-config