apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-v1-16-2.yaml

# curl -L -o cert-manager-v1-16-2.yaml -H "User-Agent: my-curl-agent" https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml