apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-v1-16-2.yaml
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--dns01-recursive-nameservers-only"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53"
  target:
    kind: Deployment
    group: apps
    version: v1
    name: cert-manager
    namespace: cert-manager
# curl -L -o cert-manager-v1-16-2.yaml -H "User-Agent: my-curl-agent" https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml