apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../../base
  - pihole-credentials-sealed-secret.yaml

secretGenerator:
  - name: pihole-credentials
    files:
      - ./pihole-credentials-sealed-secret.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"