apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../../base
  - pihole-credentials-sealed-secret.yaml

secretGenerator:
  - name: pihole-credentials
    files:
      - ./pihole-credentials-sealed-secret.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        secretRef:
          name: pihole-credentials
  target:
    kind: Deployment
    group: apps
    version: v1
    name: external-dns
    namespace: external-dns