---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-cluster
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo