---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgCDlWPzN8GeYZZMBRI76JpJd+3w3J5W77YJ5/IyNbmZW9AsxFLqT63KzwlNREk3khW4lCJ5x4yWaHqCAqgxkJwuXDSQmC/SSiKWTeT8Yos8Sup4cCC8Yx0baquZjMDG58pNYj5fB03rGdJMZS4wTU7I465o5sziMYEzXNhbsKwaJSLJKERH2T/P7SlpP7k9U7FpDuZeCPGeUaFf5OxiChQoPswoUCZBsTN51mKnPrtIhXHNf5vJRWS2HZ/LEgGnES+klFh8IO+WrozaWs5DNpfBvsD6Yfqcdya2xnIBFIOb83YVsR+KvfP7u52GHROqsaVXAq/du8jVLIvy5dZEWNkCesOCl6h5a+AR1xlCzRPABLHXragl/Wooxyg0UW0v12Mv9yH0cy4902DiSUFnzgquVuiV5nkr2knuXyF2anf2ZvqDPt88Hyhcv8eLGUTyL+U0xs1Hhnf+bHGhdQ5qzUx8cRKlJrnrkiChGBq/vsB1Z0A4zxdpebMhHRG7ZOF+0q0jIyVMu1JtpI8aNdjQb7h7iD4EILewkrdAS8bIgxCozyz9TAV9peyABSGacsrzxnB9IU2ym4qMjaXbhb2cR5644KnINoZLOULTrWxCgBezNjcCChwlIY1I2Y2YlQCPwenyNUtFJpPWydt5UCxTmV0IWRsxO5EjuN30WtuIewMTKAYfGH3fJFQJz5nkTS7kKM8hYsFrsyfkj39dr5zammqsRKwJAy+HKtFlSk/rhfgpJs7Vcjj9yXt0/RFv5J0bc9wSon4cH63Q2UqC01EC0SMK4G/63CF43+FpVtvZ4SwPehbvgCF0DMyFz3SlExI=
    username: AgA8ID4i+MVU+E3quHGsHdVcbH/mAQRpiO9Dmzr7VGVUvogY9CPR38xyxyYoRElIq7sM/rfBOzzmgtzOZPVVzfPcb4DYLmhlZJ2Y6nijDHolH0I8XzItLxRv26D44c6recQzZYF4U0ydKDb7HCZb3AvlQsXebiImUunLIInrfyCvmPE/rqRJCUtfpbzS8axxj638ez6AmHpSqY0MbezSK5GGFTu1vNpNw5JmWKpkbopQjN2VNAzY86EtlZPIA4jCj5xvK/KA+ndCM40uqQXRDguUEg9nd529Ehj7NLlyolFS9nUh0GnWiHv0SvhvN1Ntw2bstPUZ0AhIxM5mLSP7FEXCyCXQjEXYQYuNMufD3NTjaTMpPJgn9FiCSLU39joWa6beL4chB2Gn7PUs9GObuaCgo4LMdl5mfQD8v2HnH6QTVjwyB9RkNPNzxUcN/n4fCdYmtwV4Hc66Vqw1khszdQ4LxTtS0EyPHDPBZ0MuIkVk4BtRQc9DbRGWy314cWzwE2XUrqrQu+tmBEO25y5p1HfPUULo//b2McvKM64Kr9bcPjrM5cjGzU9iIX5UWXa1rivs/PMK05OS5zw+blqivMHKjeAUvs9TjIC3iLAQXd+Rf9LQ8ZbnHzXjBvhi/YZRSaOnv7ZgSzXqHsikMQ8hYBwN0GkqLts/AbG66MWUsqwgUKwHuoQOlXPh75sq1Rq6PxjjzkQN5Do=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: github-token
      namespace: flux-system
