---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgCq1K/MhK9GF3h6+/7/kVUtf4o4MR7F/bOjzH4IVZ8g3jgWuK3MNPbB4eZ3p+Kf8p6f8rmFxNgUvqL/kCKLpLRBcVpg3XWPKJxjwbVpJL+ymy7qKpmKm9ZczOCkTnA8W4EVYLiFyFtgRoskGJmsCY0DEgRTNGsCXhLLWusYZIsgvPnhYup0LG79plMmI8O0UnUFfg6bvWXsbfNjvdBnOQjrATIQzLQ2lL54IeSjJjP1cPYoD63m1TZT+XTglnISPmf3cHRcAW3yLpShuloELGJVtIB0wixsbB5aztREZhkBhZ4pKarfx439S+pLRdYWaYr7EpJOw1rRv8VNNIOKso0j+n6+MoEjv5GSWxsZgYaOseD7AIDP2QuPO+nA3yHuxBESJWMdN/aJASDCieF9f3vtI2Va/D0aeslN0S2/rjW6aNhTEL3cVXVl4pZh3u7SpklYgBXwruF5CKuEuBx8QCHeVQ+pDSg2uq7i3qDc9KGEGlhjJv1CAvVkCHvMNHrvkF+OxYsrghrrxxZVjVbvJvGAH+3cvYSlYM51qIm1B/Q0tGbGxMJNngsz8tcQ15w6OBeT/8a4rxDYq8RNG9CnHC+u2MK155seYY/4M1+k5Qkuer9gcVQGzfb0NKrnH5zQoN9hVP4Y62DOxyjyplMO8dwfHc6SU+bkN5LNwskkobxisI4w5vZQmb4Y582lZ5vkgtKEqXCPC6WZ7e60xMmulYpoqUROzEKDu1mrTYgYw1h277R0fpqjmmgs4yDDuqjmv0tkAjVLxvPbq+i2G1xSbXCLR8ZFuUzumOy81C2Eyy2+yowrKMbDwsvQt62us1o=
    username: AgB8CJI6e8LM7Z44A3OXChx5IKgyEfLfxnzv2NQaB0Qoya1V4aYFM3lVpviBmv5LRDpz/N6e7pGrAvZ9nahJboDaeNhUh1ZxE36RDMPAoXCrS78w0yA51wU/9iTiRL4bcWWtiX3mc9/z0UefShegEduRZagLqrySa5fqk9zHLtEO4Ltbb5x2GnavjorkNAeVRyd3B4gl5obDS3JSsDN8O7cBgCG1bwTPPrpWgeh3nwII1eVodrEdMO5HDQbJo4Tzw7w9v+qPW3sC27PBgYjSBOM/wc9UZn6BKzT2ZVl0dxSmGrRnaj6XakeU5IgXCbX9dDQ556Y58idEF5owxHbQ75cMUKFAwP50BKaXhxK7Lc7Mhueg7I0X1D4RlXnBYpzMpgcd1GZroaBE0wQszWtK3Q7OaUYeAXdJh8eIvTvhFN/FnwvFmiuaZDazHyKu5Dhd56oOT18zINUTYghnxP+EWo06UP2vK7GeLZYEPYM42Z0+W1twmI6f6XLHRlIw3SK5O/DaY4988+vXXO3kKlcYP10yAnf71AYz+qxMllalqVVZBjrzGf9PXbyk8Kl+r4Y77sgn3onyQ0hnowlKwJVgZvioznIl1j1uT2BEB18dUBkrW20z27VJL6F+Tlg2yJ0TXUKCg3qxEjVzsd/tor0DKMLGIUFqFlrYDQ4CZT8QKw0NgL2Sf2QAzV7iZ56sCgo26RWMfO6pUc0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: github-token
      namespace: flux-system
