---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgCIOqrzV6o79ILXx3M4wHqQoJyH6AsUdquaLv8T3wXlszDyRUlES+omViwZbrek8bjHfvqZbOokSUCb32JyF/E6ezMff7iUkByJxwGzaL8fOSiMetg1aBnWMHBWTovwnZKM69OehtP7tRZyadyAyY/riAGaGl5s0CtAOur6HQeRfXrhvFIJKZ45QbMJ1F3RqwYAbQvBV+TvxNR9rz7OCAQsalVqYfyGQKtNpY7AQEyRabPha+YXbkxwTE7mYUqiU3oT4G3tl9X+XciupEaoszMN/D1KWFTj6QbF1sOeEWtMXNx+hsy25ly32YVGlTWfHQNuCLbkPrUMuzQZDfEtu+/yvbwl9yJp8qf9arsSF7JyokMWvGymmcRvH78XJjhq14hZVzYsbW39mT4koHQyX7i3ZxnbJYv+J+eIrjxoQR6JM3O3eIJp/piOumRSwA93ashvk12ZGIfe98ZBtn3ju2/Pqp6T0knZZvI4fZGBrW2/PEZ1FWRCrpPCXewyFPAMwoPIU8i29OiLGynTyJ+z2GUGIeHdqPMUKHvbDYuP6AMlqcZ3eFrIQJcXqUECHlMoR5iz2xz2ut0GrEzL5CHfNc1MLLq+Nlx0QPhh2Hsi10lqZsBUHye+7RHYRVIHSknYvivBJj/06cFt1EXap0bgLxdxJqcSZH/fhFvO5A3xoUjT/nQAW3cBEK10biLleBAj919iRwnVTsTrHFDq9FBFVOCxpVHxd/rlTNfYwvOf28AsuMmzibmUvnPogxls2G4TXuWyMGiTNTqHrBKeGen81LYcppN3K1MoIitNZg1dYFExr25JPHCFnL/t6J0rbCM=
    username: AgBg4Ph8v23bVOgWpeZv/u1rfKFmI1yq3o5CBFUXn5RPBtxT/k0UmoQZE+xLKL+5plELhqlUjgA6G3hzYFZLINbsJmPlWkKxDMSqhkRqeNsHqCBIOBktKPsZQ14AAepwqK8BkaXbSa1ZEMNVmpfDIiv+2nGSgqDFCqpWOhvPN9ah0nDorIbPlBI1+/brXMgJpKB/Zt3pin9ymZ/M4fKh3SOTlczDlPNDUt/bFARrNSCr7mwbXdVa7EBqf7RhpFnUTZac17jDapuzOLBcaFGQ1hLdY8i7oWkHWemvSaZTbTLmwVfuXPTYgTb6NaVaV3e3u7pb184p/yeNiq5OK5Y5p4XEeNSwLTKHzJQQcywnMp3tEIQ3nPoWJMzxWR5n84XnSyaXmn2Hvz2eRkQGFc7o2jpushf4r7sp1HupMfVsDAc/ak9T4/Vu7i/Oob357U3gSc8aF6Y966ahTkz0qgAAleXQY4eWCo8jGYKcDFHtlqF6cpYkav8bRrJ5E6dZmjZPABfeoxC8NhWA8WNku2qG2mSCllhnpDqWBfBJK/so5z+hYYH/Oa6AgHloJsPZb1yA6xKlLHXYhnJ+tb/RSEscaKlNqYuyzivxJv50I9c2imChXrkS0yyG/tVi8nkJc/NcIzbHAIUsbL1gzUYRgFjtg2PFIU68/czTJZjBj6tQdegEmHvQCDKcF71Kb7UGhbWyZBoJjekLAew=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: github-token
      namespace: flux-system
