apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base
  - github-token-sealed-secret.yaml
  - git-repository-source.yaml
  - cluster-kustomization.yaml

secretGenerator:
  - name: github-token
    files:
      - ./github-token-sealed-secret.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"