apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openvpn-credentials-sealed-secret.yaml
  - ../../base

secretGenerator:
  - name: openvpn-credentials
    files:
      - ./openvpn-credentials-sealed-secret.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DNS_ADDRESS
        value: 10.255.255.1
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: TZ
        value: America/Chicago
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_HOSTNAMES
        value: "dfw-414.windscribe.com,dfw-86.windscribe.com"
  target:
    kind: Deployment
    group: apps
    version: v1
    name: qbittorrent
    namespace: media-server