apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openvpn-credentials-sealed-secret.yaml
  - ../../base

secretGenerator:
  - name: openvpn-credentials
    files:
      - ./openvpn-credentials-sealed-secret.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"