apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vpn-credentials-sealed-secret.yaml
  - ../../base

secretGenerator:
  - name: vpn-credentials
    files:
      - ./vpn-credentials-sealed-secret.yaml
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

#patches:
#- patch: |-
#    - op: add
#      path: /spec/template/spec/containers/0/env/-
#      value:
#        name: DNS_ADDRESS
#        value: 10.255.255.1
#    - op: add
#      path: /spec/template/spec/containers/0/env/-
#      value:
#        name: TZ
#        value: America/Chicago
#  target:
#    kind: Deployment
#    group: apps
#    version: v1
#    name: qbittorrent
#    namespace: media-server