---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    API_TOKEN: AgAYTpt3KiBAepVe2QwByQHdZ3kPnzNBSBah33uJ0apesrkke6oYk4KxABuBlwuwX+wW5UnoDjOxeF5THdPvOP87OL2b1zrZAZKX8bf4JEe5gUm9CLGMEaqrsIZ7i8tzc1NJQas5TdU5qcSZLZznJd9W1fELQvL4OOvX1gaXJr261JsF9RbUlUf1IHgzc4cAj2pfIEQBP+6Jr7IehJv8W2TsMBVVkXXuColeO2ywOZ+ovGNi+fImCCEP6cxxj8B6GSITUKGfwJ8EARQGCcerSVU/AZDi8vbXtTdFxornFc9HjNU101mZcgU9iLJaKPYZA7ok7LCiYGyQ2AGMhO9P73LQNZZYsJkFSJFJPCasPVuzFvBldGaEGqWIC5GSctCEwrnlNn9lIAg1flTymf5JCaYpMXD1NjHCzWM/vorXdsMUMoUQWwHCMCDOD5zmrGT4PNMaL8HxC4EiKaPEgodyprPcy//jVi77m8MWKnST8hM4b7LO/jVrTWPmvUZ5nD6gaIKpuZbyhUaZfG6GHJcKXcfTHA0+kQkJj3ojftuqwdagTOtV6ZtTb9FYBMAprQhE3AK4e/TI1ThSE49flzXHQpRb77dd3ROb0xFx+bDvnmkzQGrN91NV1sT/GVhtthxl765EiaakmPIB1Ochg3C+k4OLGseXsb3vsQEGb8zXmC5qzw6ILNF2ejC/6btcOe/kHQgFWcfBJrpi1IK+lsp18cdrHmYmQ0w0+Xvu7yXO2WI+1Uncj4eCJ80E
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
