apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-server
resources:
  - namespace.yaml
  - pvc.yaml
  - jackett.yaml
  - qbittorrent.yaml
  - flareresolverr.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - jellyfin.yaml