---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  storageClassName: nfs-hdd-media-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvshows
spec:
  storageClassName: nfs-hdd-media-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4000Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  storageClassName: nfs-hdd-media-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4000Gi